version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: tr_test_db
      MYSQL_USER: docker            #用意しているが利用していない
      MYSQL_PASSWORD: docker        #用意しているが利用していない
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/init-scripts:/docker-entrypoint-initdb.d # 初期化スクリプトをマウント
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root!
    ports:
    - 8080:80